# -*- coding: utf-8 -*-
"""modul_penjumlahan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ox_sfCEJczWM3mOX1DIHqyrisp6MutuW
"""

def penjumlahan (angka_1, angka_2):
  jumlah = angka_1 + angka_2
  return jumlah